(function (root, factory) { if (typeof define === 'function' && define.amd) { define([], factory); } else if (typeof module === 'object' && module.exports) { module.exports = factory(); module.exports.default = module.exports } else { root.sfnt2woff = factory(); } }(typeof self !== 'undefined' ? self : this, function () { var sfnt2woff={}; sfnt2woff.instantiateWasm=function(importObject, receiveInstance){ fetch('sfnt2woff.wasm').then(response => response.arrayBuffer()).then(bytes => WebAssembly.instantiate(bytes, importObject)).then(result => receiveInstance(result.instance)); };

var a;a||(a=typeof sfnt2woff !== 'undefined' ? sfnt2woff : {});var aa=Object.assign({},a),c=(b,d)=>{throw d;},k="object"==typeof window,m="function"==typeof importScripts,ba="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,ca=!k&&!ba&&!m;if(a.ENVIRONMENT)throw Error("Module.ENVIRONMENT has been deprecated. To force the environment, use the ENVIRONMENT compile-time option (for example, -s ENVIRONMENT=web or -s ENVIRONMENT=node)");
var n="",p,q,r;function da(b){if(!(b instanceof t)){var d=b;b&&"object"==typeof b&&b.stack&&(d=[b,b.stack]);u("exiting due to exception: "+d)}}var fs,v,x;
if(ba){if("object"!=typeof process||"function"!=typeof require)throw Error("not compiled for this environment (did you build to HTML and try to run it not on the web, or set ENVIRONMENT to something - like node - and run it someplace else - like on the web?)");n=m?require("path").dirname(n)+"/":__dirname+"/";x=()=>{v||(fs=require("fs"),v=require("path"))};p=function(b,d){x();b=v.normalize(b);return fs.readFileSync(b,d?void 0:"utf8")};r=b=>{b=p(b,!0);b.buffer||(b=new Uint8Array(b));assert(b.buffer);
return b};q=(b,d,g)=>{x();b=v.normalize(b);fs.readFile(b,function(e,h){e?g(e):d(h.buffer)})};1<process.argv.length&&process.argv[1].replace(/\\/g,"/");process.argv.slice(2);"undefined"!=typeof module&&(module.exports=a);process.on("uncaughtException",function(b){if(!(b instanceof t))throw b;});process.on("unhandledRejection",function(b){throw b;});c=(b,d)=>{if(noExitRuntime||0<y)throw process.exitCode=b,d;da(d);process.exit(b)};a.inspect=function(){return"[Emscripten Module object]"}}else if(ca){if("object"==
typeof process&&"function"===typeof require||"object"==typeof window||"function"==typeof importScripts)throw Error("not compiled for this environment (did you build to HTML and try to run it not on the web, or set ENVIRONMENT to something - like node - and run it someplace else - like on the web?)");"undefined"!=typeof read&&(p=function(b){return read(b)});r=function(b){if("function"==typeof readbuffer)return new Uint8Array(readbuffer(b));b=read(b,"binary");assert("object"==typeof b);return b};q=
function(b,d){setTimeout(()=>d(r(b)),0)};"function"==typeof quit&&(c=(b,d)=>{if(y)throw d;da(d);quit(b)});"undefined"!=typeof print&&("undefined"==typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!=typeof printErr?printErr:print)}else if(k||m){m?n=self.location.href:"undefined"!=typeof document&&document.currentScript&&(n=document.currentScript.src);n=0!==n.indexOf("blob:")?n.substr(0,n.replace(/[?#].*/,"").lastIndexOf("/")+1):"";if("object"!=typeof window&&"function"!=
typeof importScripts)throw Error("not compiled for this environment (did you build to HTML and try to run it not on the web, or set ENVIRONMENT to something - like node - and run it someplace else - like on the web?)");p=b=>{var d=new XMLHttpRequest;d.open("GET",b,!1);d.send(null);return d.responseText};m&&(r=b=>{var d=new XMLHttpRequest;d.open("GET",b,!1);d.responseType="arraybuffer";d.send(null);return new Uint8Array(d.response)});q=(b,d,g)=>{var e=new XMLHttpRequest;e.open("GET",b,!0);e.responseType=
"arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?d(e.response):g()};e.onerror=g;e.send(null)}}else throw Error("environment detection error");var ea=a.print||console.log.bind(console),u=a.printErr||console.warn.bind(console);Object.assign(a,aa);aa=null;Object.getOwnPropertyDescriptor(a,"fetchSettings")&&z("`Module.fetchSettings` was supplied but `fetchSettings` not included in INCOMING_MODULE_JS_API");A("arguments","arguments_");A("thisProgram","thisProgram");a.quit&&(c=a.quit);
A("quit","quit_");assert("undefined"==typeof a.memoryInitializerPrefixURL,"Module.memoryInitializerPrefixURL option was removed, use Module.locateFile instead");assert("undefined"==typeof a.pthreadMainPrefixURL,"Module.pthreadMainPrefixURL option was removed, use Module.locateFile instead");assert("undefined"==typeof a.cdInitializerPrefixURL,"Module.cdInitializerPrefixURL option was removed, use Module.locateFile instead");assert("undefined"==typeof a.filePackagePrefixURL,"Module.filePackagePrefixURL option was removed, use Module.locateFile instead");
assert("undefined"==typeof a.read,"Module.read option was removed (modify read_ in JS)");assert("undefined"==typeof a.readAsync,"Module.readAsync option was removed (modify readAsync in JS)");assert("undefined"==typeof a.readBinary,"Module.readBinary option was removed (modify readBinary in JS)");assert("undefined"==typeof a.setWindowTitle,"Module.setWindowTitle option was removed (modify setWindowTitle in JS)");assert("undefined"==typeof a.TOTAL_MEMORY,"Module.TOTAL_MEMORY has been renamed Module.INITIAL_MEMORY");
A("read","read_");A("readAsync","readAsync");A("readBinary","readBinary");A("setWindowTitle","setWindowTitle");assert(!ca,"shell environment detected but not enabled at build time.  Add 'shell' to `-s ENVIRONMENT` to enable.");var B;
function A(b,d){Object.getOwnPropertyDescriptor(a,b)||Object.defineProperty(a,b,{configurable:!0,get:function(){z("Module."+b+" has been replaced with plain "+d+" (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}})}
function fa(b,d){b="'"+b+"' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)";d&&(b+=". Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you");return b}function ha(b){Object.getOwnPropertyDescriptor(a,b)||Object.defineProperty(a,b,{configurable:!0,get:function(){z(fa(b,!1))}})}function C(b,d){Object.getOwnPropertyDescriptor(a,b)||(a[b]=()=>z(fa(b,d)))}var D;a.wasmBinary&&(D=a.wasmBinary);A("wasmBinary","wasmBinary");
var noExitRuntime=a.noExitRuntime||!1;A("noExitRuntime","noExitRuntime");"object"!=typeof WebAssembly&&z("no native wasm support detected");var E,F=!1;function assert(b,d){b||z("Assertion failed"+(d?": "+d:""))}var ia="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;"undefined"!=typeof TextDecoder&&new TextDecoder("utf-16le");var H,I,J,K;
function ja(){var b=E.buffer;H=b;a.HEAP8=new Int8Array(b);a.HEAP16=new Int16Array(b);a.HEAP32=J=new Int32Array(b);a.HEAPU8=I=new Uint8Array(b);a.HEAPU16=new Uint16Array(b);a.HEAPU32=K=new Uint32Array(b);a.HEAPF32=new Float32Array(b);a.HEAPF64=new Float64Array(b)}a.TOTAL_STACK&&assert(5242880===a.TOTAL_STACK,"the stack size can no longer be determined at runtime");var L=a.INITIAL_MEMORY||16777216;A("INITIAL_MEMORY","INITIAL_MEMORY");
assert(5242880<=L,"INITIAL_MEMORY should be larger than TOTAL_STACK, was "+L+"! (TOTAL_STACK=5242880)");assert("undefined"!=typeof Int32Array&&"undefined"!==typeof Float64Array&&void 0!=Int32Array.prototype.subarray&&void 0!=Int32Array.prototype.set,"JS engine does not provide full typed array support");assert(!a.wasmMemory,"Use of `wasmMemory` detected.  Use -s IMPORTED_MEMORY to define wasmMemory externally");assert(16777216==L,"Detected runtime INITIAL_MEMORY setting.  Use -s IMPORTED_MEMORY to define wasmMemory dynamically");
var M;function ka(){var b=N();assert(0==(b&3));J[b+4>>2]=34821223;J[b+8>>2]=2310721022;J[0]=1668509029}function O(){if(!F){var b=N(),d=K[b+4>>2];b=K[b+8>>2];34821223==d&&2310721022==b||z("Stack overflow! Stack cookie has been overwritten, expected hex dwords 0x89BACDFE and 0x2135467, but received 0x"+b.toString(16)+" 0x"+d.toString(16));1668509029!==J[0]&&z("Runtime error: The application has corrupted its heap memory area (address zero)!")}}var la=new Int16Array(1),ma=new Int8Array(la.buffer);
la[0]=25459;if(115!==ma[0]||99!==ma[1])throw"Runtime error: expected the system to be little-endian! (Run with -s SUPPORT_BIG_ENDIAN=1 to bypass)";var na=[],oa=[],pa=[],qa=[],P=!1,ra=!1,y=0;function sa(){var b=a.preRun.shift();na.unshift(b)}assert(Math.imul,"This browser does not support Math.imul(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");assert(Math.fround,"This browser does not support Math.fround(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");
assert(Math.clz32,"This browser does not support Math.clz32(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");assert(Math.trunc,"This browser does not support Math.trunc(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");var Q=0,R=null,S=null,T={};
function ta(){Q++;a.monitorRunDependencies&&a.monitorRunDependencies(Q);assert(!T["wasm-instantiate"]);T["wasm-instantiate"]=1;null===R&&"undefined"!=typeof setInterval&&(R=setInterval(function(){if(F)clearInterval(R),R=null;else{var b=!1,d;for(d in T)b||(b=!0,u("still waiting on run dependencies:")),u("dependency: "+d);b&&u("(end of list)")}},1E4))}a.preloadedImages={};a.preloadedAudios={};
function z(b){if(a.onAbort)a.onAbort(b);b="Aborted("+b+")";u(b);F=!0;throw new WebAssembly.RuntimeError(b);}function ua(){z("Filesystem support (FS) was not included. The problem is that you are using files from JS, but files were not used from C/C++, so filesystem support was not auto-included. You can force-include filesystem support with  -s FORCE_FILESYSTEM=1")}a.FS_createDataFile=function(){ua()};a.FS_createPreloadedFile=function(){ua()};
function va(){return U.startsWith("data:application/octet-stream;base64,")}function V(b){return function(){var d=a.asm;assert(P,"native function `"+b+"` called before runtime initialization");assert(!ra,"native function `"+b+"` called after runtime exit (use NO_EXIT_RUNTIME to keep it alive after main() exits)");d[b]||assert(d[b],"exported native function `"+b+"` not found");return d[b].apply(null,arguments)}}var U;U="sfnt2woff.wasm";if(!va()){var wa=U;U=a.locateFile?a.locateFile(wa,n):n+wa}
function xa(){var b=U;try{if(b==U&&D)return new Uint8Array(D);if(r)return r(b);throw"both async and sync fetching of the wasm failed";}catch(d){z(d)}}
function ya(){if(!D&&(k||m)){if("function"==typeof fetch&&!U.startsWith("file://"))return fetch(U,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+U+"'";return b.arrayBuffer()}).catch(function(){return xa()});if(q)return new Promise(function(b,d){q(U,function(g){b(new Uint8Array(g))},d)})}return Promise.resolve().then(function(){return xa()})}
function W(b){for(;0<b.length;){var d=b.shift();if("function"==typeof d)d(a);else{var g=d.h;"number"==typeof g?void 0===d.g?za(g)():za(g)(d.g):g(void 0===d.g?null:d.g)}}}var X=[];function za(b){var d=X[b];d||(b>=X.length&&(X.length=b+1),X[b]=d=M.get(b));assert(M.get(b)==d,"JavaScript-side Wasm function table mirror is out of date!");return d}var Y=[null,[],[]];
function Aa(b,d){var g=Y[b];assert(g);if(0===d||10===d){b=1===b?ea:u;d=0;for(var e=d+NaN,h=d;g[h]&&!(h>=e);)++h;if(16<h-d&&g.subarray&&ia)d=ia.decode(g.subarray(d,h));else{for(e="";d<h;){var f=g[d++];if(f&128){var l=g[d++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|l);else{var G=g[d++]&63;if(224==(f&240))f=(f&15)<<12|l<<6|G;else{if(240!=(f&248)){var w="Invalid UTF-8 leading byte 0x"+f.toString(16)+" encountered when deserializing a UTF-8 string in wasm memory to a JS string!";B||(B={});B[w]||
(B[w]=1,u(w))}f=(f&7)<<18|l<<12|G<<6|g[d++]&63}65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}d=e}b(d);g.length=0}else g.push(d)}
var Da={emscripten_memcpy_big:function(b,d,g){I.copyWithin(b,d,d+g)},emscripten_resize_heap:function(b){var d=I.length;b>>>=0;assert(b>d);if(1073741824<b)return u("Cannot enlarge memory, asked to go up to "+b+" bytes, but the limit is 1073741824 bytes!"),!1;for(var g=1;4>=g;g*=2){var e=d*(1+.2/g);e=Math.min(e,b+100663296);var h=Math;e=Math.max(b,e);h=h.min.call(h,1073741824,e+(65536-e%65536)%65536);a:{e=h;try{E.grow(e-H.byteLength+65535>>>16);ja();var f=1;break a}catch(l){u("emscripten_realloc_buffer: Attempted to grow heap from "+
H.byteLength+" bytes to "+e+" bytes, but got error: "+l)}f=void 0}if(f)return!0}u("Failed to grow the heap from "+d+" bytes to "+h+" bytes, not enough memory!");return!1},exit:function(b){noExitRuntime||0<y?u("program exited (with status: "+b+"), but keepRuntimeAlive() is set (counter="+y+") due to an async operation, so halting execution but not exiting the runtime or preventing further async execution (you can use emscripten_force_exit, if you want to force a true shutdown)"):(O(),Ba(),W(pa),Ca(),
Y[1].length&&Aa(1,10),Y[2].length&&Aa(2,10),ra=!0);if(!(noExitRuntime||0<y)){if(a.onExit)a.onExit(b);F=!0}c(b,new t(b))},fd_close:function(){z("it should not be possible to operate on streams when !SYSCALLS_REQUIRE_FILESYSTEM");return 0},fd_seek:function(){z("it should not be possible to operate on streams when !SYSCALLS_REQUIRE_FILESYSTEM")},fd_write:function(b,d,g,e){for(var h=0,f=0;f<g;f++){var l=J[d>>2],G=J[d+4>>2];d+=8;for(var w=0;w<G;w++)Aa(b,I[l+w]);h+=G}J[e>>2]=h;return 0},setTempRet0:function(){}};
(function(){function b(f){a.asm=f.exports;E=a.asm.memory;assert(E,"memory not found in wasm exports");ja();M=a.asm.__indirect_function_table;assert(M,"table not found in wasm exports");oa.unshift(a.asm.__wasm_call_ctors);Q--;a.monitorRunDependencies&&a.monitorRunDependencies(Q);assert(T["wasm-instantiate"]);delete T["wasm-instantiate"];0==Q&&(null!==R&&(clearInterval(R),R=null),S&&(f=S,S=null,f()))}function d(f){assert(a===h,"the Module object should not be replaced during async compilation - perhaps the order of HTML elements is wrong?");
h=null;b(f.instance)}function g(f){return ya().then(function(l){return WebAssembly.instantiate(l,e)}).then(function(l){return l}).then(f,function(l){u("failed to asynchronously prepare wasm: "+l);U.startsWith("file://")&&u("warning: Loading from a file URI ("+U+") is not supported in most browsers. See https://emscripten.org/docs/getting_started/FAQ.html#how-do-i-run-a-local-webserver-for-testing-why-does-my-program-stall-in-downloading-or-preparing");z(l)})}var e={env:Da,wasi_snapshot_preview1:Da};
ta();var h=a;if(a.instantiateWasm)try{return a.instantiateWasm(e,b)}catch(f){return u("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return D||"function"!=typeof WebAssembly.instantiateStreaming||va()||U.startsWith("file://")||"function"!=typeof fetch?g(d):fetch(U,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(d,function(l){u("wasm streaming compile failed: "+l);u("falling back to ArrayBuffer instantiation");return g(d)})})})();
return{}})();a.___wasm_call_ctors=V("__wasm_call_ctors");a._sfnt2woff=V("sfnt2woff");a._malloc=V("malloc");a._free=V("free");a.___errno_location=V("__errno_location");var Ca=a.___stdio_exit=V("__stdio_exit"),Ba=a.___funcs_on_exit=V("__funcs_on_exit"),Ea=a._emscripten_stack_init=function(){return(Ea=a._emscripten_stack_init=a.asm.emscripten_stack_init).apply(null,arguments)};a._emscripten_stack_get_free=function(){return(a._emscripten_stack_get_free=a.asm.emscripten_stack_get_free).apply(null,arguments)};
a._emscripten_stack_get_base=function(){return(a._emscripten_stack_get_base=a.asm.emscripten_stack_get_base).apply(null,arguments)};var N=a._emscripten_stack_get_end=function(){return(N=a._emscripten_stack_get_end=a.asm.emscripten_stack_get_end).apply(null,arguments)};a.stackSave=V("stackSave");a.stackRestore=V("stackRestore");a.stackAlloc=V("stackAlloc");a.dynCall_jiji=V("dynCall_jiji");C("intArrayFromString",!1);C("intArrayToString",!1);C("ccall",!1);C("cwrap",!1);C("setValue",!1);
C("getValue",!1);C("allocate",!1);C("UTF8ArrayToString",!1);C("UTF8ToString",!1);C("stringToUTF8Array",!1);C("stringToUTF8",!1);C("lengthBytesUTF8",!1);C("stackTrace",!1);C("addOnPreRun",!1);C("addOnInit",!1);C("addOnPreMain",!1);C("addOnExit",!1);C("addOnPostRun",!1);C("writeStringToMemory",!1);C("writeArrayToMemory",!1);C("writeAsciiToMemory",!1);C("addRunDependency",!0);C("removeRunDependency",!0);C("FS_createFolder",!1);C("FS_createPath",!0);C("FS_createDataFile",!0);
C("FS_createPreloadedFile",!0);C("FS_createLazyFile",!0);C("FS_createLink",!1);C("FS_createDevice",!0);C("FS_unlink",!0);C("getLEB",!1);C("getFunctionTables",!1);C("alignFunctionTables",!1);C("registerFunctions",!1);C("addFunction",!1);C("removeFunction",!1);C("getFuncWrapper",!1);C("prettyPrint",!1);C("dynCall",!1);C("getCompilerSetting",!1);C("print",!1);C("printErr",!1);C("getTempRet0",!1);C("setTempRet0",!1);C("callMain",!1);C("abort",!1);C("keepRuntimeAlive",!1);C("zeroMemory",!1);
C("stringToNewUTF8",!1);C("emscripten_realloc_buffer",!1);C("ENV",!1);C("withStackSave",!1);C("ERRNO_CODES",!1);C("ERRNO_MESSAGES",!1);C("setErrNo",!1);C("inetPton4",!1);C("inetNtop4",!1);C("inetPton6",!1);C("inetNtop6",!1);C("readSockaddr",!1);C("writeSockaddr",!1);C("DNS",!1);C("getHostByName",!1);C("Protocols",!1);C("Sockets",!1);C("getRandomDevice",!1);C("traverseStack",!1);C("convertFrameToPC",!1);C("UNWIND_CACHE",!1);C("saveInUnwindCache",!1);C("convertPCtoSourceLocation",!1);
C("readAsmConstArgsArray",!1);C("readAsmConstArgs",!1);C("mainThreadEM_ASM",!1);C("jstoi_q",!1);C("jstoi_s",!1);C("getExecutableName",!1);C("listenOnce",!1);C("autoResumeAudioContext",!1);C("dynCallLegacy",!1);C("getDynCaller",!1);C("dynCall",!1);C("callRuntimeCallbacks",!1);C("wasmTableMirror",!1);C("setWasmTableEntry",!1);C("getWasmTableEntry",!1);C("handleException",!1);C("runtimeKeepalivePush",!1);C("runtimeKeepalivePop",!1);C("callUserCallback",!1);C("maybeExit",!1);C("safeSetTimeout",!1);
C("asmjsMangle",!1);C("asyncLoad",!1);C("alignMemory",!1);C("mmapAlloc",!1);C("reallyNegative",!1);C("unSign",!1);C("reSign",!1);C("formatString",!1);C("PATH",!1);C("PATH_FS",!1);C("SYSCALLS",!1);C("getSocketFromFD",!1);C("getSocketAddress",!1);C("JSEvents",!1);C("registerKeyEventCallback",!1);C("specialHTMLTargets",!1);C("maybeCStringToJsString",!1);C("findEventTarget",!1);C("findCanvasEventTarget",!1);C("getBoundingClientRect",!1);C("fillMouseEventData",!1);C("registerMouseEventCallback",!1);
C("registerWheelEventCallback",!1);C("registerUiEventCallback",!1);C("registerFocusEventCallback",!1);C("fillDeviceOrientationEventData",!1);C("registerDeviceOrientationEventCallback",!1);C("fillDeviceMotionEventData",!1);C("registerDeviceMotionEventCallback",!1);C("screenOrientation",!1);C("fillOrientationChangeEventData",!1);C("registerOrientationChangeEventCallback",!1);C("fillFullscreenChangeEventData",!1);C("registerFullscreenChangeEventCallback",!1);C("registerRestoreOldStyle",!1);
C("hideEverythingExceptGivenElement",!1);C("restoreHiddenElements",!1);C("setLetterbox",!1);C("currentFullscreenStrategy",!1);C("restoreOldWindowedStyle",!1);C("softFullscreenResizeWebGLRenderTarget",!1);C("doRequestFullscreen",!1);C("fillPointerlockChangeEventData",!1);C("registerPointerlockChangeEventCallback",!1);C("registerPointerlockErrorEventCallback",!1);C("requestPointerLock",!1);C("fillVisibilityChangeEventData",!1);C("registerVisibilityChangeEventCallback",!1);
C("registerTouchEventCallback",!1);C("fillGamepadEventData",!1);C("registerGamepadEventCallback",!1);C("registerBeforeUnloadEventCallback",!1);C("fillBatteryEventData",!1);C("battery",!1);C("registerBatteryEventCallback",!1);C("setCanvasElementSize",!1);C("getCanvasElementSize",!1);C("demangle",!1);C("demangleAll",!1);C("jsStackTrace",!1);C("stackTrace",!1);C("getEnvStrings",!1);C("checkWasiClock",!1);C("flush_NO_FILESYSTEM",!1);C("writeI53ToI64",!1);C("writeI53ToI64Clamped",!1);
C("writeI53ToI64Signaling",!1);C("writeI53ToU64Clamped",!1);C("writeI53ToU64Signaling",!1);C("readI53FromI64",!1);C("readI53FromU64",!1);C("convertI32PairToI53",!1);C("convertU32PairToI53",!1);C("setImmediateWrapped",!1);C("clearImmediateWrapped",!1);C("polyfillSetImmediate",!1);C("uncaughtExceptionCount",!1);C("exceptionLast",!1);C("exceptionCaught",!1);C("ExceptionInfo",!1);C("CatchInfo",!1);C("exception_addRef",!1);C("exception_decRef",!1);C("Browser",!1);C("funcWrappers",!1);
C("getFuncWrapper",!1);C("setMainLoop",!1);C("wget",!1);C("tempFixedLengthArray",!1);C("miniTempWebGLFloatBuffers",!1);C("heapObjectForWebGLType",!1);C("heapAccessShiftForWebGLHeap",!1);C("GL",!1);C("emscriptenWebGLGet",!1);C("computeUnpackAlignedImageSize",!1);C("emscriptenWebGLGetTexPixelData",!1);C("emscriptenWebGLGetUniform",!1);C("webglGetUniformLocation",!1);C("webglPrepareUniformLocationsBeforeFirstUse",!1);C("webglGetLeftBracePos",!1);C("emscriptenWebGLGetVertexAttrib",!1);
C("writeGLArray",!1);C("AL",!1);C("SDL_unicode",!1);C("SDL_ttfContext",!1);C("SDL_audio",!1);C("SDL",!1);C("SDL_gfx",!1);C("GLUT",!1);C("EGL",!1);C("GLFW_Window",!1);C("GLFW",!1);C("GLEW",!1);C("IDBStore",!1);C("runAndAbortIfError",!1);C("warnOnce",!1);C("stackSave",!1);C("stackRestore",!1);C("stackAlloc",!1);C("AsciiToString",!1);C("stringToAscii",!1);C("UTF16ToString",!1);C("stringToUTF16",!1);C("lengthBytesUTF16",!1);C("UTF32ToString",!1);C("stringToUTF32",!1);C("lengthBytesUTF32",!1);
C("allocateUTF8",!1);C("allocateUTF8OnStack",!1);a.writeStackCookie=ka;a.checkStackCookie=O;ha("ALLOC_NORMAL");ha("ALLOC_STACK");var Z;function t(b){this.name="ExitStatus";this.message="Program terminated with exit("+b+")";this.status=b}S=function Fa(){Z||Ga();Z||(S=Fa)};
function Ga(){function b(){if(!Z&&(Z=!0,a.calledRun=!0,!F)){O();assert(!P);P=!0;W(oa);if(a.onRuntimeInitialized)a.onRuntimeInitialized();assert(!a._main,'compiled without a main, but one is present. if you added it from JS, use Module["onRuntimeInitialized"]');O();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var d=a.postRun.shift();qa.unshift(d)}W(qa)}}if(!(0<Q)){Ea();ka();if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)sa();
W(na);0<Q||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b(),O())}}a.run=Ga;if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();Ga();
return sfnt2woff; }));
